Application/config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users

  post '/add', to: 'ordenando#add'
  post '/limpar', to: 'ordenando#limpar'
  post '/inverter', to: 'ordenando#inverter' # Alteração aqui
  post '/misturar', to: 'ordenando#misturar'

  get "up" => "rails/health#show", as: :rails_health_check
end

Application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Application/app/models/user.rb
class User < ApplicationRecord
end

Application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Application/app/controllers/ordenando_controller.rb
class OrdenandoController < ApplicationController
  protect_from_forgery with: :null_session

  def add
    valor = params[:valor]
    render json: { valor: valor }, status: :ok
  end

  def limpar
    # Lógica para limpar os valores
    render json: { message: "Valores limpos com sucesso" }, status: :ok
  end

  def inverter
    # Lógica para inverter os valores
    render json: { message: "Valores invertidos com sucesso" }, status: :ok
  end

  def ordenar
    # Lógica para ordenar os valores
    render json: { message: "Valores ordenados com sucesso" }, status: :ok
  end
end

Application/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]


  # No seu controlador Rails
def ordenar
  valores = params[:valores]
  sorted_valores = valores.sort_by(&:to_i)
  render json: sorted_valores
end

# No seu controlador Rails
def misturar
  valores = params[:valores]
  mixed_valores = valores.shuffle
  render json: mixed_valores
end


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :date, :description, :done)
    end
end

Application/app/helpers/application_helper.rb
module ApplicationHelper
end

Application/app/helpers/ordenando_helper.rb
module OrdenandoHelper
end

Application/app/helpers/users_helper.rb
module UsersHelper
end

Application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Application/app/views/layouts/ordenando/ordenando.html.erb
<%= form_with(url: ordernar_path, method: :post) do |form| %>
  <%= form.label :valor %>
  <%= form.number_field :valor %>
  <%= form.submit "Adicionar" %>
<% end %>

Application/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :done, style: "display: block" %>
    <%= form.check_box :done %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Application/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= user.date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= user.description %>
  </p>

  <p>
    <strong>Done:</strong>
    <%= user.done %>
  </p>

</div>

Application/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

Application/app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ordenando valores</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>   
    <main style="margin:100px">
        <h1>Ordenando Valores</h1>
        <form id="formOrdenar">
            <label>Valores (separados por vírgula)</label>
            <br>
            <input class="form-control"  id="valores" type="text">
            <br><br> 
            <button class="btn btn-primary" type="button" onclick="add()">Adicionar</button> 
            <button class="btn btn-primary" type="button" onclick="misturar()">Inverter</button>
            <button class="btn btn-primary" type="button" onclick="ordenar()">Ordenar</button> 
            <button class="btn btn-primary" type="button" onclick="limpar()">Limpar</button>

            <div> <!-- Lista de valores adicionados -->
                <ul id="valoresAdicionados"></ul> 
            </div>
            
            <!-- Mostra os valores adicionados -->
            <div id="valoresAdicionadosInfo"></div>
        </form>   
        <!-- Código JavaScript -->
        <script>
            function add() {
                var valores = document.getElementById("valores").value.split(",");
                fetch('/add', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRF-Token': '<%= form_authenticity_token %>'
                    },
                    body: JSON.stringify({ valores: valores })
                })
                .then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        throw new Error('Erro ao adicionar valores');
                    }
                })
                .then(data => {
                    document.getElementById("valoresAdicionadosInfo").innerText = "Valores adicionados: " + data.valores.join(", ");
                    mostrarValoresAdicionados(data.valores);
                })
                .catch(error => {
                    console.error('Erro:', error);
                });
            }

            function mostrarValoresAdicionados(valores) {
                var listaValoresAdicionados = document.getElementById("valoresAdicionados");
                listaValoresAdicionados.innerHTML = ""; // Limpa a lista antes de adicionar os novos valores

                valores.forEach(valor => {
                    var li = document.createElement("li");
                    li.textContent = valor;
                    listaValoresAdicionados.appendChild(li);
                });
            }

            function limpar() {
                fetch('/limpar', { method: 'POST' })
                .then(response => {
                    if (response.ok) {
                        document.getElementById("valoresAdicionados").innerHTML = "";
                        document.getElementById("valoresAdicionadosInfo").innerText = "";
                    } else {
                        throw new Error('Erro ao limpar valores');
                    }
                })
                .catch(error => console.error('Erro:', error));
            }

            function ordenar() {
                fetch('/inverter', { method: 'POST' }) // Alteração aqui
                .then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        throw new Error('Erro ao inverter valores'); // Alteração aqui
                    }
                })
                .then(data => {
                    console.log('Invertido:', data); // Alteração aqui
                    mostrarValoresAdicionados(data.valores); // Alteração aqui
                })
                .catch(error => console.error('Erro:', error));
            }

            function misturar() {
                fetch('/misturar', { method: 'POST' })
                .then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        throw new Error('Erro ao misturar valores');
                    }
                })
                .then(data => {
                    console.log('Misturado:', data);
                    mostrarValoresAdicionados(data.valores);
                })
                .catch(error => console.error('Erro:', error));
            }
        </script>
    </main>
</body>
</html>

Application/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

Application/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>